trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test
  displayName: 'dotnet test'
- script: dotnet pack --configuration $(buildConfiguration)
  displayName: 'dotnet pack $(buildConfiguration)'
